name: Second workflow
on: issues
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
  issue:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{toJson(github.event)}}"
